---
- name: Common provision
  hosts: [control, worker]
  become: true
  gather_facts: false
  roles:
    - wait_connection
    - apt_sources
    - chrony
    - disable_swap

- name: Load balancer provision
  hosts: control
  become: true
  gather_facts: false
  pre_tasks:
    - name: End play if running on Yandex Cloud
      ansible.builtin.meta: end_host
      when: yandex_cloud | default(false)
  roles:
    - haproxy
    - keepalived

- name: Kubernetes provision
  hosts: [control, worker]
  become: true
  gather_facts: false
  roles:
    - docker_repo
    - kubernetes

- name: Worker provison
  hosts: [worker]
  become: true
  gather_facts: false
  roles:
    - disk_label
    - mount
    - longhorn

- name: Apply kubernetes manifests
  hosts: [control]
  become: false
  gather_facts: false
  roles:
    - role: vault
    - role: kubernetes_apply
      kubernetes_apply_manifests:
        - manifests/certmanager-selfsigned-issuer.yml
        - manifests/certmanager-gateway.yml
        - manifests/eg-nodeport.yml
        - manifests/gateway.yml
        - manifests/http-to-https-redirect.yml
        - manifests/wordpress-mariadb-secret.yml
        - manifests/wordpress-mariadb-service-headless.yml
        - manifests/wordpress-mariadb-service.yml
        - manifests/wordpress-mariadb.yml
    - role: vault_config
    - role: kubernetes_apply
      kubernetes_apply_manifests:
        - manifests/vault-client-tls-cert.yml
        - manifests/wordpress-angie-config.yml
        - manifests/wordpress-config.yml
        - manifests/wordpress-pvc.yml
        - manifests/wordpress-service.yml
        - manifests/wordpress.yml
        - manifests/wordpress-httproute.yml
...
