---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: default
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/name: wordpress
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
...
