---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mariadb
  namespace: default
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: mariadb
data:
  mariadb-password: '{{ wordpress_mariadb_password |
    ansible.builtin.b64encode }}'
  mariadb-root-password: '{{ wordpress_mariadb_root_password |
    ansible.builtin.b64encode }}'
type: Opaque
...
