---
- name: Update vault general configuration
  community.hashi_vault.vault_write:
    url: '{{ vault_config_url }}'
    validate_certs: '{{ vault_config_validate_certs }}'
    auth_method: token
    token: '{{ vault_config_token }}'
    path: '{{ item.key }}'
    data: '{{ item.value }}'
  loop: '{{ vault_config_write | ansible.builtin.dict2items }}'
  loop_control:
    label: '{{ item.key }}'
...
